### PR TITLE
[NO-JIRA] Add tests for dark mode

### PR DESCRIPTION
**Pull request by tiagoengel**
+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-react-native/blob/master/CONTRIBUTING.md)

Remember to include the following changes:
+ [x] `UNRELEASED.md`
+ [x] `README.md`
+ [x] Tests
+ [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINES.md)_

### CODE REVIEW

**Comment by shaundon** [comment]
Also, is `0.0.0` the correct version to use for a new package? I might be wrong but I thought that caused issues and it needed to be at least `0.0.1`

**Comment by tiagoengel** [comment]
Yes I thought about automatically applying for every test. Is not that simple because you can only add the wrapper inside the `create` function (or `shallow` and `render` from enzyme) so there is no way to wrap the component from the outside. 

The only other solution is to mock the native bridge to return `dark` or to mock the appearance methods to use a specific variation.

Mocking appearance can be done but is very error prone and hard to debug understand. Consider this example where 'react-native-bpk-test-utils` is also globally mocking the appearance methods.

```javascript
import BpkText from `react-native-bpk-component-text`
// This will work to mock the `Subject` bellow but the text component above will be out of sync
import { describeWithColorScheme } from 'react-native-bpk-test-utils`

import Subject from '.'
```

```javascript
import { describeWithColorScheme } from 'react-native-bpk-test-utils`
// This will now fail to mock the `appearance` package we are including another package that requires it afterwards.
import BpkText from `react-native-bpk-component-text`

import Subject from '.'
```

There are more edge cases but in general is very fragile unless we write the mock logic explicitly in each file, which is them very verbose. 

Mocking the native bridge to return `dark` or `light` for the initial value can work but that will require running all tests for both modes, which will create a lot of unnecessary test duplication because a lot tests don't need to run in dark mode.

**Comment by tiagoengel** [comment]
About the version I'm not sure, but `0.0.1` makes more sense, I'll update. This is also not supposed to be published, it's for internal tests

**Comment by tiagoengel** [comment]
@shaundon other than the reasons above I think a more explicit approach like this is better, is not really a lot of overhead and we can control which tests we want to run in dark mode

**Comment by shaundon** [comment]
@tiagoengel Thanks for the detailed explanation, your logic makes sense :)

**Pull request merged**
